apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: telepresence-cleaner
  namespace: default
spec:
  schedule: "0 23 * * 5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: telepresence-cleaner
          containers:
            - name: cleaner
              image: cytram/kubernetes-cleaner:latest
              env:
                - name: CLEANER_NAMESPACE
                  value: "default"
                - name: CLEANER_POD
                  value: "telepresence.*"
          restartPolicy: Never
