apiVersion: v1
kind: ServiceAccount
metadata:
  name: telepresence-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: telepresence
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telepresence
  namespace: default
subjects:
  - kind: ServiceAccount
    name: telepresence-cleaner
    namespace: default
roleRef:
  kind: Role
  name: telepresence
  apiGroup: rbac.authorization.k8s.io
